_BASE_: maskformer2_R50_bs16_50ep.yaml
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    RES5_MULTI_GRID: [1, 1, 1]  # not used

INPUT:
  CROP:
    CROP_INSTANCE: True
    ENABLED: False
    SIZE: [0.9, 0.9]
    TYPE: relative_range
  
  IMAGE_SIZE: 1333
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "sobav2_instance"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  ANNOTATIONS_DATASETROOT: "dataset/SOBA/annotations"
  IMAGE_DATASETROOT: "dataset/SOBA/SOBA"

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  # STEPS: (80000, )
  # MAX_ITER: 90000
  STEPS: (20000, 40000)
  MAX_ITER: 45000
  CHECKPOINT_PERIOD: 9000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
TEST:
  EVAL_PERIOD: 9000

DATASETS:
  TRAIN: ("soba_cast_shadow_train_full",)
  TEST: ("soba_cast_shadow_val_full",)
OUTPUT_DIR: "./output_sobav2"